name: semver-release-branch
description: Uses Github branch to release semver version of the code
author: shobhitDream11
branding:
    icon: 'paperclip'
    color: 'white'
jobs:
    audit:
        runs-on: ubuntu-latest
        inputs:
          repo-token:
            description: 'Branches to update'
            required: false
          github-run-number:
            description: 'Github run number'
            required: false
        steps:
        - uses: actions/checkout@v1
        - name: Zip folder
          run: zip -r releases.zip .
        - name: Release to Github
          run: echo "Releasing"
        
        - name: Create Github Release
          id: create-new-release
          uses: actions/create-release@v1
          env:
            GITHUB_TOKEN: ${{ inputs.repo-token }}
          with:
            tag_name: v${{ github.event.inputs.github-run-number }}       
            release_name: Realease V${{ github.event.inputs.github-run-number }}
        
        - name:  Upload Asset
          uses: actions/upload-release-asset@v1
          env:
            GITHUB_TOKEN: ${{ github.event.inputs.repo-token }}
          with:
            upload_url: ${{ steps.create-new-release.outputs.upload_url }}
            asset_path: ./releases.zip
            asset_name: site-v${{ github.event.inputs.github-run-number }}.zip
            asset_content_type: application/zip
